name: Kesandra
version: '${project.version}'
main: net.lexicodes.kesandra.Kesandra
api-version: 1.13
authors: [ LexiCodesOfficial, Almondz ]
description: A Multi Purpose Server Management Plugin For Spigot And Forks Of It!
website: https://lexicodes.net
commands:
  repair:
    description: Repairs Your Tool
    usage: /<command>
    aliases: [fix, krepair, kfix]

  broadcast:
    description: broadcast
    usage: /<command> <msg>
    aliases: [adminshout]
